### ISSUE TITLE
windows suport

### ISSUE THREAD

**Issue by jb3** [AnonGuy/dotfiles#1]
hi

does this work on windows???
thanks

**Comment by jerbob** [comment]
hi jos-b, i wil add windows suport thanks

**Comment by jb3** [comment]
thank you anonguy

I look forward to using your linux dot files on my wind downs system!

**Comment by jerbob** [comment]
hi 

[we have windows suport now!!!](https://github.com/AnonGuy/dotfiles/releases/tag/windows-suport)
thanks

**Comment by jb3** [comment]
this is so freaking cool man, thanks for the fast response time
